name: http_request
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  url_launcher: ^6.1.10
  url_launcher_android: ^6.0.27
  url_launcher_ios: ^6.1.4
  intl: ^0.17.0

 
  cupertino_icons: ^1.0.2
  flutter_masked_text2: ^0.9.1
  shared_preferences: ^2.3.3
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  image: 4.0.17
  lints: 3.0.0

  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/logo.png"
  adaptive_icon_background: "assets/images/icons/logo.png"

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/tablas/
    - assets/wallpapers/
